name: lifeline
description: A secure, fast, and reliable emergency contact platform for Nigeria.
publish_to: 'none' # private project

version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

  # Networking
  http: ^1.2.2
  dio: ^5.9.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5

  # Offline storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Maps & Geolocation
  google_maps_flutter: ^2.3.0
  geolocator: ^14.0.2
  geocoding: ^2.0.6

  # AdMob
  google_mobile_ads: ^6.0.0

  # Sharing
  share_plus: ^12.0.1

  # URL Launching
  url_launcher: ^6.3.1
  flutter_phone_direct_caller: ^2.1.1
  permission_handler: ^12.0.0

  # Localization & Fonts
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.3.3

  # Animations
  animated_text_kit: ^4.2.2
  animations: ^2.1.1

  # The Provider
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/data/nigeria_states_lgas.json
    #- assets/images/app_icon.png
    #- assets/icons/fast.png
    #- assets/icons/verified.png
    #- assets/icons/offline.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
